### ISSUE TITLE
oauth2 version end of life (EOL)

### ISSUE THREAD

**Issue by jeremyw** [cronofy/cronofy-ruby#102]
This gem depends on oauth2 version "~> 1.0", but version 1.4.x has reached EOL.

Installation produces the following warning:

```
Post-install message from oauth2:

You have installed oauth2 version 1.4.10, which is EOL.
No further support is anticipated for the 1.4.x series.

OAuth2 version 2 is released.
There are BREAKING changes, but most will not encounter them, and upgrading should be easy!

Please see:
• https://github.com/oauth-xx/oauth2#what-is-new-for-v20
• https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md

Please upgrade, report issues, and support the project! Thanks, |7eter l-|. l3oling
```

**Comment by AdamWhittingham** [comment]
Thanks for raising this - we’re going to see what we can do to broaden the version requirement to minimize any chance of disruption.

**Comment by etipton** [comment]
@AdamWhittingham bump on this -- any chance this can be prioritized?

**Comment by AdamWhittingham** [comment]
@etipton Thanks for the nudge and sorry this didn't get wrapped up; we're taking a look!

**Comment by AdamWhittingham** [comment]
Thanks for your patience everyone - [v0.40.0](https://rubygems.org/gems/cronofy/versions/0.40.0) has been shipped to address this.
