### ISSUE TITLE
Query slots not supported for real time scheduling

### ISSUE THREAD

**Issue by atainton** [cronofy/cronofy-ruby#110]
According to the Cronofy [changelog](https://changelog.cronofy.com/specific-slots-for-availability-queries-267834), we should be able to specify query slots in the availability hash when calling `real_time_scheduling` on the Cronofy client. I took a look through the code and I see no reference to `query_slots`. 

When will query slots be supported by this gem?

**Comment by kr-mykyta** [comment]
Hi @atainton,

Hope you are well and thanks for reaching out!

We will aim to release an update to the Ruby SDK to include `query_slots` in RTS in the next couple of weeks. I will let you know as soon as it's out, but will also keep you updated on the progress, for example in case of an unexpected delay.

Best,
Mykyta.

**Comment by kr-mykyta** [comment]
Hi @atainton,

Just wanted to give you a quick update that we're still working on this change. This will be released as soon as possible, as I know you have been waiting for a while now.

Apologies for the delay!

Best,
Mykyta.

**Comment by CronofyMatt** [comment]
Hi @atainton,

Just wanted to let you know that this has now been [deployed as an update to the Cronofy Ruby SDK](https://rubygems.org/gems/cronofy/versions/0.41.0).

Please let us know if you have any issues!

All the best,
Matt
