### ISSUE TITLE
Get a 400 bad request when trying to refresh the token - what am i doing wrong? 

### ISSUE THREAD

**Issue by gregory** [cronofy/cronofy-ruby#14]
``` rb
client = Cronofy::Client.new(access_token: access_token, refresh_token: refresh_token)
[3] pry(main)> client.refresh_access_token
Cronofy::BadRequestError: 400 Bad Request
from /usr/local/bundle/gems/cronofy-0.8.3/lib/cronofy/errors.rb:85:in `raise_error'
[4] pry(main)>
```

**Comment by gshutler** [comment]
Hi @gregory, are you setting your client ID and secret via environment variables? Those being missing are the first thing that springs to mind.

If that's not the problem then can you email support@cronofy.com with the email address of the account you're trying to refresh and the client ID if your application. That will help us look into it further.

**Comment by kcampos** [comment]
Getting the same thing. Other operations are fine, client ID and secret are fine. If I hit cronofy api directly with same ID, secret and refresh token I get a 200 OK. Pretty sure this is just a problem in the gem.

**Comment by gshutler** [comment]
HI @kcampos could you provide some sample code so we can try and reproduce the issue, along with Ruby version and so forth?

If you're concerned that anything in it is sensitive then feel free to email support@cronofy.com instead.

**Comment by kcampos** [comment]
`ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]`
`cronofy (0.8.3)`
`omniauth-cronofy (0.4.0)`
`Rails 4.2.6`

Using omniauth-cronofy I successfully get back an auth, from which I can use the access_token and refresh_token directly against the cronofy API without issue. I can also use the cronofy gem with these tokens successfully for many operations. The only one failing for me is:

`Cronofy::Client.new(access_token: access_token, refresh_token: refresh_token).refresh_access_token`

which gives me a `Cronofy::BadRequestError: 400 Bad Request` error

**Comment by kcampos** [comment]
My cronofy application is in development mode right now, not sure if that would have anything to do with it. Do you not allow refreshes on those tokens? I did not the expire time on them is only a few hours.

**Comment by kcampos** [comment]
FWIW I'm getting the same 400 response hitting the `/oauth/token` endpoint using Faraday. But if I use Postman I get a 200.

**Comment by kcampos** [comment]
I got Faraday to work by posting payload as JSON instead of www-form-urlencoded. So this certainly seems to be related to the request method

**Comment by kcampos** [comment]
Well this is embarrassing. Turns out this was all due to a typo in one of my docker containers env file for the `CLIENT_ID`. I noticed a discrepency in behavior between them and finally discovered that. So I withdraw my #doublestamp of this issue. Sorry for the confusion.

**Comment by gshutler** [comment]
No problem @kcampos, thanks for letting us know you've got to the bottom of it.

We'll take a look at the gem and/or the 400 response to see if there's some way we can make it easier for people to debug.

**Comment by gshutler** [comment]
@kcampos was the typo you mentioned in the name of the environment variable or the value? I'm guessing the latter as [we have some guards to flag a missing ID/secret](https://github.com/cronofy/cronofy-ruby/blob/d8aa18c3e63a27a9e502f402748d771bb1aeb447/lib/cronofy/auth.rb#L102) but it would help us think about ways to help people.

**Comment by kcampos** [comment]
The value
