### ISSUE TITLE
Read Events?

### ISSUE THREAD

**Issue by railsjedi** [cronofy/cronofy-ruby#6]
https://www.cronofy.com/developers/api/#read-events

is there a helper for reading events? if so, I can add it to Readme.md. if not, i'll add it to the gem itself

**Comment by railsjedi** [comment]
nm, i found it. https://github.com/cronofy/cronofy-ruby/blob/master/lib/cronofy/client.rb#L129-L181

**Comment by gshutler** [comment]
Yes, there is a [`Client#read_events`](https://github.com/cronofy/cronofy-ruby/blob/3790d5b47cb40ba200874e3166e00c625dac6600/lib/cronofy/client.rb#L129-L172) method.

Sorry the README doesn't include it.

**Comment by railsjedi** [comment]
no prob, thanks!
