### ISSUE TITLE
Request for more documentation

### ISSUE THREAD

**Issue by edwinthinks** [cronofy/cronofy-ruby#65]
Hello!

I am really enjoying working with the Cronofy service. I was wondering if there are plans to add more documentation (maybe in the README) for other usage cases like Smart Invites?

Thank you, 
Edwin M. Mak

**Comment by AdamWhittingham** [comment]
Hi Edwin,

Sorry for this issue being left around so long- hopefully you've seen out [API docs site](https://docs.cronofy.com/developers/api/); feel free to get in touch if that doesn't cover everything you're looking for!
