### ISSUE TITLE
Upgrade Hashie

### ISSUE THREAD

**Issue by connorshea** [cronofy/cronofy-ruby#83]
Hashie 4.x is available but the gem currently uses Hashie 3.x, could we upgrade it? It's causing conflicts in our Gemfile :(

**Comment by AdamWhittingham** [comment]
Hi @connorshea, we've just released [Version 0.36.1](https://rubygems.org/gems/cronofy/versions/0.36.1) with a wider spec, so Hashie 4.x should now work happily.

**Comment by connorshea** [comment]
Thank you!

**Comment by shanearrowsmith** [comment]
@AdamWhittingham any chance you could do the same trick for Hashie 5.x? We're having similar Gemfile conflicts.

**Comment by AdamWhittingham** [comment]
@shanearrowsmith Sorted - [V0.41.1](https://rubygems.org/gems/cronofy/versions/0.41.1) supports Hasie 5.X 👍

**Comment by shanearrowsmith** [comment]
Thanks @AdamWhittingham - much appreciated!
