### ISSUE TITLE
Allow revoking authorization via sub instead of token

### ISSUE THREAD

**Issue by connorshea** [cronofy/cronofy-ruby#86]
Currently, the `revoke_authorization` method uses the `token` automatically: https://github.com/cronofy/cronofy-ruby/blob/fc9cd41fbf52140963600da4e1663279263571b4/lib/cronofy/client.rb#L736-L738

But [the API docs](https://docs.cronofy.com/developers/api/authorization/revoke/#param-sub) say that you can use the `sub` to revoke an authorization. The Ruby gem should support that.

**Comment by AdamWhittingham** [comment]
Hi @connorshea,

We've just released [0.37.0](https://rubygems.org/gems/cronofy/versions/0.37.0) of the gem, which adds `revoke_by_token(token)` and `revoke_by_sub(sub)` to the Client.

If you have any problems with it, please let us know at support@cronofy.com

**Comment by connorshea** [comment]
Thanks!
