### ISSUE TITLE
Data centre parameter could be more explicit in README

### ISSUE THREAD

**Issue by Eeyurrn** [cronofy/cronofy-ruby#89]
Cronofy allows developers to [specify which data center](https://docs.cronofy.com/developers/data-centers/) they wish to use when instantiating the client 

In this section of the  README.md, it's not quite explicit how you specify this.

https://github.com/cronofy/cronofy-ruby/blob/0e19e3880dbb5f7b3f67f3f54edd9b3813516279/README.md#L35-L40

With a bit of [digging](https://github.com/cronofy/cronofy-ruby/blob/fc9cd41fbf52140963600da4e1663279263571b4/lib/cronofy/client.rb#L45)  I found the key `data_centre` with UK spelling which is slightly different from the general spelling used in the [docs](https://docs.cronofy.com/developers/data-centers/) 

Would it be possible to update the docs to make it more explicit about specifying the data center like the example below?

```ruby
cronofy = Cronofy::Client.new(
  client_id:     'CLIENT_ID',
  client_secret: 'CLIENT_SECRET',
  access_token:  'ACCESS_TOKEN',
  refresh_token: 'REFRESH_TOKEN',
  data_centre:   'DATA_CENTER_REGION' # will use US by default
)
```

Cheers!

**Comment by AdamWhittingham** [comment]
Hi @Eeyurrn, we've just released version 0.37.1 which should sort this out 👍 

If you have any problems, please let us know at support@cronofy.com
