### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by websoft-foryou** [cronofy/cronofy-ruby#96]
Hi, Everyone.
I am going to use Push Notification after booking an appointment by calling Cronofy API.
I can get the hook after notification channel. But I can't get the any hooks after booking an appointment.
How should I do?

**Comment by Nevett** [comment]
Hi!

The best way to get support using the Cronofy API is to contact support@cronofy.com

It sounds like you might be expecting to receive a push notification after making an API call to create an event in a user's calendar. We won't ever send push notifications to your application for a change that your application initiated - only changes from external sync. That's documented here: https://docs.cronofy.com/developers/push-notifications/#receiving-notifications

If you're still having problems, or if you're not seeing the expected notifications after making an _external_ change to a synchronized calendar, please reach out to the support team and we'll get you up and running! :)

Thanks
Chris @ Cronofy
